### ISSUE TITLE
Tools for Consistent, Parseable Log Formatting

### ISSUE THREAD

**Issue by petergoldstein** [ioquatix/rubydns#42]
This is intended as a discussion about a potential feature.  If we can agree on goals and details I can probably do a PR

In most of RubyDNS' logging, the log message starts with either angle brackets or square brackets, which generally contain either a message id. a response id, or a query id.  Some messages start with an empty set of angle brackets, and at least one message (the startup message) has no brackets at all.

I'd like to have a consistent format that is easily parseable by automated tools.  Some goals:
1. The type of data (message id, response id, query id) associated with a log message should be unambiguous
2. The presence or absence of such data should be unambiguous regardless of the log message (i.e. Even if I start my log message with '<', it should not be possible to confuse the data and message setions)
3. RubyDNS should include a Logger formatter that makes it easy to format logs in the preferred manner
4. All examples should use this format

@ioquatix Any thoughts?  If you agree with the above goals, do you have preferences for the format?

**Comment by ioquatix** [comment]
I believe it should be possible to revisit this.

I've rewritten RubyDNS on top of a new `Async` framework where all function calls are essentially nested. Therefore, if you generates a prefix you could pass this through all functions doing logging.

**Comment by ioquatix** [comment]
A single transaction operates on a single Fiber so you could set a finer-local UUID and use that for logging.

**Comment by ioquatix** [comment]
Let me know if this is something you are still interested in and we can discuss this further.

**Comment by petergoldstein** [comment]
@ioquatix Thanks, but I'm not using RubyDNS anymore, so this isn't something I need.

**Comment by ioquatix** [comment]
Just FYI, we resolved this issue using a new gem called console, and in async, logging with request ids is now task scoped.

https://gist.github.com/ioquatix/6eafd57374ef73d299fdfddfab2f4979?ts=2

shows an example of how to do this.
