### ISSUE TITLE
Gem broken by celluloid 0.16.1

### ISSUE THREAD

**Issue by justicel** [ioquatix/rubydns#55]
It appears that the celluloid authors aren't abiding by sym-versioning rules, as the update to 0.16.0 was released a few days ago and completely breaks your gem. Can you lock to 0.16.0 in your gemspec and release a new version, or fix for the new gem versions?

**Comment by ioquatix** [comment]
Yes, this is a problem. I'm currently working on it and hope to have it solved in the next few days.

**Comment by ioquatix** [comment]
@digitalextremist celluloid supervision broke a heap of stuff for lots of people :(

**Comment by digitalextremist** [comment]
I am going to yank `0.16.1` right now. It was requested by someone who didn't need it by the time I did it, but never mentioned that. I am sorry for the trouble.

**Comment by digitalextremist** [comment]
It is now gone. `0.17.1.1` is reported as stable from what I've seen. `0.16.1` should never have happened.

**Comment by ioquatix** [comment]
@digitalextremist this was a big problem man, lots and lots of people have issues, did you see the size of those linked threads? jeezus.

**Comment by ioquatix** [comment]
I've just cut a new release 1.0.2 which ties RubyDNS to celluloid 0.16.0 which is an interim fix. There will be a release of RubyDNS 2.0 soon which has a better fix and also updates to celluloid 0.17.0 but that still requires a bit of work.

**Comment by ioquatix** [comment]
> I am going to yank 0.16.1 right now.

Thanks for sorting that out..

**Comment by digitalextremist** [comment]
Just to doubly mention: `0.16.0` is totally gone. I am in the process of working on `ECell` before coming into `0.18.0` work, but I will instead do some maintenance where needed and get out a `0.17.5` perhaps, across all top-level gems, and move along the supporting gems where needed. Again, I am sorry about the trouble. The `0.16.1` was unneeded but it was presented to me as if it was. I ought to have ignore the request, but I try to keep all running implementations stable as possible if I can.

**Comment by digitalextremist** [comment]
( Fixed comment to read `0.16.1` and not `0.16.0` )

**Comment by digitalextremist** [comment]
And for the record, if `0.16.1` were completely clean ( as it ought to be, but for some reason is not ) it did not "go out of sequence" with semver, it was a point release on the `0.16.*` line, even if that is now not the active release series.

**Comment by ioquatix** [comment]
@digitalextremist yeah i get that it was just a point release, it cold be anything, back port a security fix, etc. The reality is it caused a bit of chaos :D

**Comment by justicel** [comment]
@digitalextremist Thanks for yanking the .1 release, I think that was the right thing to do for the community as a whole. When I said that the new point release wasn't abiding by semantic rules, it was because there were unintentional backward compatibility changes. Appreciate the help!

**Comment by ioquatix** [comment]
This has been fixed, but please feel free to ask any questions if there are further issues relating to this issue.
