### ISSUE TITLE
How to disable logging?

### ISSUE THREAD

**Issue by do11** [ioquatix/rubydns#62]
Hello,

Excuse me, but, how to disable any output to stdout when running server?

**Comment by ioquatix** [comment]
@do11 There is a new 2.0.0.pre.rc1 which uses `Async.logger` so if you change the log level of that logger there will be zero output. Alternatively, you can specify per-server log output, e.g.

```ruby
MyServer.new(logger: Logger.new($stderr, level: Logger::WARN))
```
