### ISSUE TITLE
flakey-dns.rb example is incorrect

### ISSUE THREAD

**Issue by do11** [ioquatix/rubydns#63]
`flakey-dns.rb` example is using `false` to pass control to `otherwise` handler which is not working. Actually it needs using `next!` method. Thus, example is wrong.

For example, if I request `microt.com` it is not resolving.

This is classical and loved by everybody _wrong example case_. I expect arrogant response like "it was just an example", like many [ruby coders love to say](https://github.com/igrigorik/em-proxy/issues/53).

**Comment by ioquatix** [comment]
Thanks for reporting this and I will sort it out :) I appreciate all reports like this and the time it took you to figure out what was wrong and what to do about it.

**Comment by ioquatix** [comment]
This has been merged. Thanks so much for fixing this and for your extended patience. I really appreciate your effort to improve this project.
